### ISSUE TITLE
Testing Kumuluzee Hystrix fault tolerance

### ISSUE THREAD

**Issue by OhMyDeera** [kumuluz/kumuluzee-fault-tolerance#1]
The documentation for the hystrix is really good, but how would someone test their microservice?
I've got a kumuluzee microservice with JWT-Auth and now i've added the Hystrix fault tolerance, but i dont see anywhere anything about testing these?
Mainly with regards to:
- CircuitBreaker
- Timeout
- BulkHead

I was just wondering how i can go about doing these without having to run my microservice and then have another application hitting the endpoints to test it.

Cheers

**Comment by MBJuric** [comment]
You can mock Hystrix commands for unit testing. However, testing Hystrix is not Kumuluz specific, so please refer to Hystrix examples and their documentation. For example: https://github.com/Netflix/Hystrix/issues/349

**Comment by OhMyDeera** [comment]
If it isnt kumuluzee specific, can it still be done without doing so in a "hacky" way? or would i have to do it through the actual Hystrix implementation?

Also is there no way to do this without mocking? such as using arquillian maybe?

**Comment by cen1** [comment]
Hystrix implementation is no longer under development. Fault tolerance in general can be tested using [arquillian](https://github.com/kumuluz/kumuluzee-testing) or weld-junit4.
